### ISSUE TITLE
Craft 4 ($entryTypeId) must be of type int, string given when trying to clone an entry type.

### ISSUE THREAD

**Issue by turnstylerj** [verbb/cloner#12]
### Describe the bug

When trying to clone an entry type on a Craft 4 install, the spinner icon just continues spinning and no project config changes happen. Checking the logs, I'm seeing:

```
2022-09-07 22:34:33 [web.ERROR] [TypeError] TypeError: craft\services\Sections::getEntryTypeById(): Argument #1 ($entryTypeId) must be of type int, string given, called in /path/to/vendor/verbb/cloner/src/controllers/CloneController.php on line 26 and defined in /path/to/vendor/craftcms/cms/src/services/Sections.php:1016
Stack trace:
#0 /path/to/vendor/verbb/cloner/src/controllers/CloneController.php(26): craft\services\Sections->getEntryTypeById('13?site=stowers...')
#1 [internal function]: verbb\cloner\controllers\CloneController->actionEntryType()
#2 /path/to/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /path/to/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /path/to/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('entry-type', Array)
#5 /path/to/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('cloner/clone/en...', Array)
#6 /path/to/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('cloner/clone/en...', Array)
#7 /path/to/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /path/to/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /path/to/web/index.php(12): yii\base\Application->run()
#10 {main} {"memory":26042496,"exception":"[object] (TypeError(code: 0): craft\\services\\Sections::getEntryTypeById(): Argument #1 ($entryTypeId) must be of type int, string given, called in /path/to/vendor/verbb/cloner/src/controllers/CloneController.php on line 26 at /path/to/vendor/craftcms/cms/src/services/Sections.php:1016)"} 
```

### Steps to reproduce

1. Install Cloner
2. Attempt to clone an entry type

### Craft CMS version

4.2.3

### Plugin version

2.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/cloner/releases/tag/2.0.1)
