### ISSUE TITLE
Doesn't work on Filesystems in Craft 4?

### ISSUE THREAD

**Issue by thijskaspers** [verbb/cloner#13]
### Describe the bug

When trying to clone a Filesystem in Craft 4 (with a Google Cloud Bucket), I get the following error:

![Schermafbeelding 2022-10-03 om 08 58 19](https://user-images.githubusercontent.com/1608184/193518013-e133a89b-3871-4015-bdd9-e44c74bbdce9.png)

**Stacktrace:**

````
TypeError: Cannot use "::class" on value of type null in /app/vendor/verbb/cloner/src/services/Filesystems.php:26
Stack trace:
#0 /app/vendor/verbb/cloner/src/controllers/CloneController.php(293): verbb\cloner\services\Filesystems->setupClonedFilesystem(NULL, 'Blog', 'blog')
#1 [internal function]: verbb\cloner\controllers\CloneController->actionFilesystem()
#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#4 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('filesystem', Array)
#5 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('cloner/clone/fi...', Array)
#6 /app/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('cloner/clone/fi...', Array)
#7 /app/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#8 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#9 /app/web/index.php(21): yii\base\Application->run()
#10 {main}
````

### Steps to reproduce

1. Install Cloner on Craft 4
2. Create a filesystem
3. Clone the filesystem by clicking on the plus icon

### Craft CMS version

4.2.5.1

### Plugin version

2.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Should be fixed in [2.0.2](https://github.com/verbb/cloner/releases/tag/2.0.2)
